name: Run Higgs Audio Generation

on:
  workflow_dispatch:  # You can trigger it manually

jobs:
  generate-audio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository (if needed)
      uses: actions/checkout@v3

    - name: Clone Higgs Audio repository
      run: |
        git clone https://github.com/boson-ai/higgs-audio.git
        cd higgs-audio

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd higgs-audio
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run generation script
      run: |
        cd higgs-audio
        python3 examples/generation.py \
          --transcript examples/transcript/multi_speaker/en_argument.txt \
          --seed 12345 \
          --out_path generation.wav
